template: ~/.claude/file-templates/init-project/api-contracts.yaml
openapi: 3.0.0
info:
  title: Project API
  version: 0.1
paths:
  /users:
    get:
      summary: List users
      x-feature-id: "F-##"           # Which feature implements this
      x-story-ids: ["US-###"]         # Which stories cover this endpoint
      x-data-events: []               # Events triggered by this endpoint
      responses:
        "200":
          description: OK