openapi: "3.0.0"
info:
  title: "Example Documentation Project API"
  version: "1.0.0"
  description: "RESTful API for authentication and analytics"

servers:
  - url: "http://localhost:3000"
    description: "Development server"
  - url: "https://api.example.com"
    description: "Production server"

paths:
  /api/auth/register:
    post:
      summary: "Register new user account"
      tags: ["Authentication"]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  minLength: 8
      responses:
        "201":
          description: "User created successfully"
        "400":
          description: "Invalid input"
        "409":
          description: "Email already exists"

  /api/auth/login:
    post:
      summary: "Authenticate user credentials"
      tags: ["Authentication"]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: "Login successful"
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  user:
                    type: object
        "401":
          description: "Invalid credentials"

  /api/dashboard/metrics:
    get:
      summary: "Fetch aggregated metrics data"
      tags: ["Dashboard"]
      security:
        - bearerAuth: []
      parameters:
        - name: timeRange
          in: query
          schema:
            type: string
            enum: ["day", "week", "month"]
      responses:
        "200":
          description: "Metrics retrieved successfully"
          content:
            application/json:
              schema:
                type: object
                properties:
                  metrics:
                    type: array
        "401":
          description: "Unauthorized"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
